wso2-extensions/identity-local-auth-fido

components/org.wso2.carbon.identity.application.authenticator.fido/pom.xml, components/org.wso2.carbon.identity.authenticator.fido.stub/pom.xml, features/org.wso2.carbon.identity.application.authenticator.fido.server.feature/pom.xml, pom.xml
=> Merge Release 5.1.1 to master

pom.xml
Reverts wso2-extensions/identity-local-auth-fido#15
=> Revert "Changed framework version"

components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/dao/DeviceStoreDAO.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/internal/FIDOAuthenticatorServiceComponent.java
=> Delete the deadstore variables

pom.xml
In [1] DeviceRegistration is importing "import com.google.common.base.MoreObjects" where "MoreObjects" is not available in guava 15 version. DeviceRegistration toString method is dependent on MoreObjects. There fore it is giving class not found exception. In order to solve this I have upgraded the guava version.
[1] https://github.com/wso2-extensions/identity-local-auth-fido/blob/master/components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/dao/DeviceStoreDAO.java#L79
solves https://github.com/wso2/product-is/issues/2756
immediately
environments.]
-
=> Upgrade the guava version

components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/util/FIDOAuthenticatorConstants.java
- This fix introduce a new configuration for `<IS_HOME>/repository/conf/identity/application-authentication.xml` file. In a Reverse proxy enabled setup the relavent server URL as the `AppID` should be configured under `FIDOAuthenticator` config in `application-authentication.xml` file as below,
```
<AuthenticatorConfig  name="FIDOAuthenticator" enabled="true">
.................................
<Parameter name="AppID">https://hostname</Parameter>
</AuthenticatorConfig>
```
- Resolves https://github.com/wso2/product-is/issues/2737
- Immediately
- The [official documentaion](https://docs.wso2.com/display/IS541/Multi-factor+Authentication+using+FIDO) need to be updated with this details.
=> Fix bad appId error when Reverse proxy enabled

components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/dao/DeviceStoreDAO.java
[List all changes you want to add here. If you fixed an issue, please
add a reference to that issue as well.]
-
environments.]
-
=> Change the debug log

components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticator.java
=> fix debug message

components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/dao/FIDO2DeviceStoreDAO.java
=> Fix SQL error

components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/dao/FIDO2DeviceStoreDAO.java
This PR removes the e.printStackTrace() added with https://github.com/wso2-extensions/identity-local-auth-fido/pull/33/files#diff-6a32d823d809819ca99ddece4f28d0deR436
=> Remove printStackTrace()

components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/common/FIDO2Constants.java, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/impl/CredentialIdApiServiceImpl.java, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/impl/DefaultApiServiceImpl.java, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/impl/FinishRegistrationApiServiceImpl.java, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/impl/StartRegistrationApiServiceImpl.java, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/impl/StartUsernamelessRegistrationApiServiceImpl.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java
Fix comments in https://github.com/wso2-extensions/identity-local-auth-fido/pull/41
=> Address PR comments.

components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java
Fix issues with registration and login for tenant users.
=> Fix tenant issue

components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/cache/FIDO2Cache.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/cache/FIDO2CacheEntry.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/cache/FIDO2CacheKey.java, pom.xml
Move the following caches to the tenant space.
- FIDO2Cache
Related Issue : wso2/product-is#11690
=> Move FIDO2 Cache to tenant space

components/org.wso2.carbon.identity.api.user.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/common/FIDO2Constants.java, components/org.wso2.carbon.identity.api.user.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/common/Util.java, components/org.wso2.carbon.identity.api.user.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/impl/CredentialIdApiServiceImpl.java, components/org.wso2.carbon.identity.api.user.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/impl/DefaultApiServiceImpl.java, components/org.wso2.carbon.identity.api.user.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/impl/FinishRegistrationApiServiceImpl.java, components/org.wso2.carbon.identity.api.user.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/impl/StartRegistrationApiServiceImpl.java
=> Block FIDO2 API endpoints for the requests with BasicAuth

components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/dao/FIDO2DeviceStoreDAO.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/util/FIDOUtil.java, pom.xml
Update yubico version
-
environments.]
-
=> Update yubico version

components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/dao/FIDO2DeviceStoreDAO.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/util/FIDOUtil.java, pom.xml
Reverts wso2-extensions/identity-local-auth-fido#68
=> Revert "Update yubico version"

components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/dao/FIDO2DeviceStoreDAO.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/util/FIDOUtil.java, pom.xml
Reverting the reverted PR for updating yubico version
Reverting wso2-extensions/identity-local-auth-fido#69
Related to https://github.com/wso2/product-is/issues/12479
=> Reverting the reverted PR for updating yubico version

components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/dao/FIDO2DeviceStoreDAO.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/util/FIDOUtil.java, pom.xml
Reverts wso2-extensions/identity-local-auth-fido#70
=> Revert "Reverting the reverted PR for updating yubico version"

pom.xml
Related issues: wso2/product-is#12485
Related PRs: https://github.com/wso2/orbit/pull/494
Bump yubico version 
Bump guava version
=> bump yubico and guava version

components/org.wso2.carbon.identity.application.authenticator.fido2/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java
- Fix origin related issue in FIDO2 authentication by using the domain (without subdomain components) of the urls'.
- According to the [webauthn documentation](https://www.w3.org/TR/webauthn-1/#relying-party-identifier), relying party identifier can be overwritten as follows.
> By default, the RP ID for a WebAuthn operation is set to the caller’s origin's effective domain. This default MAY be overridden by the caller, as long as the caller-specified RP ID value is a registrable domain suffix of or is equal to the caller’s origin's effective domain.
- Hence this fix utilize `google guava` library to extract the top private domain from the origin url.
- https://github.com/wso2/product-is/issues/13005
- Immediately
- N/A
=> Fix Origin Issue in FIDO2 Authentication Flow

components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java
- Fix fido device registration issue for email usernames
- Resolves https://github.com/wso2/product-is/issues/13002
- Immediately 
- N/A
=> Fix fido device registration issue for email usernames

components/org.wso2.carbon.identity.application.authenticator.fido/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido2/pom.xml, components/org.wso2.carbon.identity.authenticator.fido.stub/pom.xml, features/org.wso2.carbon.identity.application.authenticator.fido.server.feature/pom.xml, features/org.wso2.carbon.identity.application.authenticator.fido2.server.feature/pom.xml, pom.xml
=> change version to 5.2.11-SNAPSHOT

components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/dao/FIDO2DeviceStoreDAO.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/util/FIDO2AuthenticatorConstants.java
- Fix username mismatch in the fido registration response
- Immediately 
- N/A
=> Fix username mismatch in fido registration response

pom.xml
Upgraded Jackson version to 2.13.0 and CXF version to 3.4.5 to mitigate the known vulnerabilities
=> Upgrade jackson and cxf versions

components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/common/FIDO2Constants.java, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/common/Util.java, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/impl/CredentialIdApiServiceImpl.java, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/impl/DefaultApiServiceImpl.java, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/impl/FinishRegistrationApiServiceImpl.java, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/endpoint/impl/StartRegistrationApiServiceImpl.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/dao/FIDO2DeviceStoreDAO.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/util/FIDOUtil.java, pom.xml
=> Add update fixes to 5.2.x

components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java
- Improve user display name build logic
- Immediately 
- N/A
=> Improve user display name build logic

pom.xml
=> Yubico orbit bumped.

pom.xml
Upgrade **yubico-webauthn** version from `1.10.1.wso2v2` to `1.12.1.wso2v1`.
Related to: wso2/product-is#13048
Merge after https://github.com/wso2/orbit/pull/550
=> Upgrade yubico-webauthn version

pom.xml
Upgrade jackson version to 2.13.1, cxf version to 3.5.0 and yubico version to 1.12.1
=> [5.2.x] Upgrade third party dependencies

components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticator.java, pom.xml
- Enable support for tenant qualified URL mode
- Immediately
environments.]
-
=> Enable support for tenant qualified URL mode

pom.xml
=> Upgrade jackson and cxf libraries

components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/util/FIDOAuthenticatorConstants.java
Reverts wso2-extensions/identity-local-auth-fido#92
=> Revert "fix(constants): rename fido authn displayName"

components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/util/FIDOAuthenticatorConstants.java
Redo: https://github.com/wso2-extensions/identity-local-auth-fido/pull/92
=> Re "Revert "fix(constants): rename fido authn displayName""

pom.xml
A part of the fix for [https://github.com/wso2-enterprise/asgardeo-product/issues/12565](https://github.com/wso2-enterprise/asgardeo-product/issues/12565)
=> Upgrading jackson-databind to 2.13.4

pom.xml
=> Update jackson databind version to 2.13.4.2

components/org.wso2.carbon.identity.api.user.fido2/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido2/pom.xml, components/org.wso2.carbon.identity.authenticator.fido.stub/pom.xml, features/org.wso2.carbon.identity.application.authenticator.fido.server.feature/pom.xml, features/org.wso2.carbon.identity.application.authenticator.fido2.server.feature/pom.xml, pom.xml
Get latest changes from master and update pom to 6.0.0 major version for IPK.
=> Update pom to Major Development Version

pom.xml
Upgrade carbon kernel version to v4.9.2
=> Upgrade carbon kernel version

components/org.wso2.carbon.identity.application.authenticator.fido2/pom.xml, features/org.wso2.carbon.identity.application.authenticator.fido.server.feature/pom.xml, pom.xml
=> Update carbon-identity-framework version range

components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/internal/MetadataService.java, pom.xml
$subject
After merging below PR
- https://github.com/wso2/orbit/pull/951
environments.]
-
=> Fix some conformance test failures

pom.xml
Upgrade guava version to 32.1.1-jre
Increase guava version range up to 34.0.0
=> Upgrade guava version range up to 34.0.0

components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/dao/FIDO2DeviceStoreDAO.java, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/util/FIDO2AuthenticatorConstants.java
- Update the existing FIDO2 device store record with the new signature count without removing and add it again.
- The database should be updated with the latest signature counter value received by the authenticator device (in a single DB transaction).
- https://github.com/wso2/product-is/issues/16412
- Update the `signatureCount` value in the `FIDO2CredentialRegistration` class object.
- Pass it to `updateFIDO2SignatureCountByUsername` method, in order to update the FIDO2 device store record in a single transaction. 
- For the DB update, use `UPDATE` syntax.
- Signature Counter verification is done inside the `finishAssertion` method invoked by the `relyingParty` [1].
- If Signature Counter is not supported by the device, then counter value will always be 0 [2].
[1] - …
=> Fix FIDO 2 Signature Count Update

components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/util/FIDOAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/test/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticatorTest.java, pom.xml
Prepare the Fido Authenticator for API Based Authentication
=> Prepare the Fido Authenticator for API Based Authentication

components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/util/FIDOAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/test/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticatorTest.java, pom.xml
Modify Fido Authenticator with API_Based Authentication modifications
=> Modify Fido Authenticator with API_Based Authentication modifications

components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticator.java
[List all changes you want to add here. If you fixed an issue, please
add a reference to that issue as well.]
-
environments.]
-
=> Improve comment

components/org.wso2.carbon.identity.api.user.fido2/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/connector/FIDOAuthenticatorConfigImpl.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/internal/FIDOAuthenticatorServiceComponent.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/internal/FIDOAuthenticatorServiceDataHolder.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/util/FIDOAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/util/FIDOUtil.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/test/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticatorTest.java, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido2/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java, components/org.wso2.carbon.identity.authenticator.fido.stub/pom.xml, features/org.wso2.carbon.identity.application.authenticator.fido.server.feature/pom.xml, features/org.wso2.carbon.identity.application.authenticator.fido2.server.feature/pom.xml, pom.xml
- Add FIDO key registration support during authentication.
- Support FIDO to be configured  as first factor, second factor and with identifier first.
- Elevate the significance of the term "Passkey," while diminishing the prominence of "Security Key/ Biometrics."
- https://github.com/wso2/product-is/issues/16372
=> Add FIDO key progressive enrollment support

components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/connector/FIDOAuthenticatorConfigImpl.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/util/FIDOAuthenticatorConstants.java
- Fix incorrect redirection upon user initiated authentication cancel request
- Change the configurable parameters default value
- Relates to https://github.com/wso2/product-is/issues/16372
=> Fix incorrect redirection upon user initiated authentication cancel request

components/org.wso2.carbon.identity.application.authenticator.fido/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/internal/FIDOAuthenticatorServiceComponent.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/internal/FIDOAuthenticatorServiceDataHolder.java, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/util/FIDOAuthenticatorConstants.java, pom.xml
- $subject
- If a federated user is already provisioned in the user store, the FIDO authenticator will provide authentication and passkey enrollment support. If the user is not provisioned, an error message will be displayed.[1]
- Relates to https://github.com/wso2/product-is/issues/17425
- Relates to https://github.com/wso2/product-is/issues/16372
- https://github.com/wso2/identity-apps/pull/4475
- https://github.com/wso2/carbon-identity-framework/pull/5118
- [1] Error page
> <img width="441" alt="Error page" src="https://github.com/wso2-extensions/identity-local-auth-fido/assets/47135592/b75d6f29-9cd3-4719-9118-deb4989995ef">
=> Add federated users handling support

pom.xml
$Subject
Should be merged after:
1. https://github.com/wso2/carbon-identity-framework/pull/4981
2. https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2184
=> Upgrade Jackson dependencies to 2.15.2

components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticator.java
- $Subject
- Fix  https://github.com/wso2/product-is/issues/17490
- Fix https://github.com/wso2/product-is/issues/17480
=> Add tenant support

components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticator.java
Set message to AuthenticatorData
=> set message to AuthenticatorData

components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticator.java
=> Fix unit test failure

components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java
- Fix https://github.com/wso2/product-is/issues/18098
environments.]
-
=> Improve trusted origin validation

components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java
- Improve trusted origin validation to support origins with default 443 port
- Add additional trusted origins by removing default ports 443 and 80 to prevent origin mismatch issues.
- Fixes https://github.com/wso2/product-is/issues/18098
environments.]
-
=> Improve trusted origin validation to support origins with default 443 port

pom.xml
=> Bump jackson dependencies version

pom.xml
=> Bump guava version to 33.0.0-jre

.github/workflows/pr-builder.yml, codecov.yml, components/org.wso2.carbon.identity.api.user.fido2/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido2/pom.xml, components/org.wso2.carbon.identity.authenticator.fido.stub/pom.xml, features/org.wso2.carbon.identity.application.authenticator.fido.server.feature/pom.xml, features/org.wso2.carbon.identity.application.authenticator.fido2.server.feature/pom.xml, pom.xml
This PR adds Codecov and JaCoCo configurations to the repository.
=> [Automated]Add Codecov and JaCoCo configurations

.github/workflows/coverage-generator.yml
Modify code cov generator for jdk 8
=> [Automated]Improve Codecov for jdk 8

pom.xml
> This PR removes the spring dependency from main pom.xml
- https://github.com/wso2/product-is/issues/21159
=> Remove spring dependency from main pom.xml

pom.xml
- $subject
- https://github.com/wso2/product-is/issues/21159
- https://github.com/wso2-extensions/identity-local-auth-fido/pull/144
=> [Spring Cleanup] Remove unused modules

components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/src/main/webapp/META-INF/webapp-classloading.xml, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/src/main/webapp/WEB-INF/beans.xml, components/org.wso2.carbon.identity.application.authenticator.fido2.endpoint/src/main/webapp/WEB-INF/web.xml, features/org.wso2.carbon.identity.application.authenticator.fido2.server.feature/pom.xml, features/org.wso2.carbon.identity.application.authenticator.fido2.server.feature/resources/p2.inf
Reverts wso2-extensions/identity-local-auth-fido#144
=> Revert "[Spring Cleanup] Remove spring dependency from fido2 API endpoint"

components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/executor/FIDO2Executor.java
$subject
https://github.com/wso2/product-is/issues/24697
=> Add tenant domain to the username to handle email usernames properly

pom.xml
=> Upgrade yubico-webauthn version to 2.5.1.wso2v1

components/org.wso2.carbon.identity.application.authenticator.fido/pom.xml, components/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticator.java, pom.xml
$subject
- https://github.com/wso2/product-is/issues/25618
=> Add sp param to the fido redirect uri
